services:
  postgres:
    image: postgres:16-alpine
    container_name: labproject-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: labproject_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d labproject_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  webapi:
    container_name: labproject-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=labproject_db;Username=postgres;Password=postgrespassword
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: