// <auto-generated />
using System;
using LabProject.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabProject.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabProject.Domain.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3d2e5b1-285e-4c8d-9b5f-8c38a2e7c001"),
                            Description = "Electronic devices and digital equipment",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("b4e3f6c2-396f-4d9e-0c6a-9d49b3f8d002"),
                            Description = "Technical literature and textbooks",
                            Name = "Books"
                        },
                        new
                        {
                            Id = new Guid("c5f4a7d3-407a-4eaf-1d7b-0e5ac4a9e003"),
                            Description = "Peripherals, cables, and hardware components",
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("LabProject.Domain.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("a3d2e5b1-285e-4c8d-9b5f-8c38a2e7c001"),
                            Name = "Mechanical Keyboard",
                            Price = 89.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CategoryId = new Guid("a3d2e5b1-285e-4c8d-9b5f-8c38a2e7c001"),
                            Name = "Gaming Mouse",
                            Price = 49.50m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("b4e3f6c2-396f-4d9e-0c6a-9d49b3f8d002"),
                            Name = "CLR via C# by Jeffrey Richter",
                            Price = 54.00m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CategoryId = new Guid("c5f4a7d3-407a-4eaf-1d7b-0e5ac4a9e003"),
                            Name = "USB-C to DisplayPort Cable",
                            Price = 18.25m,
                            StockQuantity = 50
                        });
                });

            modelBuilder.Entity("LabProject.Domain.Models.Product", b =>
                {
                    b.HasOne("LabProject.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LabProject.Domain.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
